# Generated by Django 5.1.4 on 2024-12-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_feedback_image_alter_itemlist_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Price',
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
